### ISSUE TITLE
Error occurred when loading

### ISSUE THREAD

**Issue by SissyTrashQueen** [MrCrayfish/Filters#2]
Filters has failed to load correctly
BUILDING_BLOCKS

[latest.log](https://github.com/MrCrayfish/Filters/files/3694351/latest.log)

**Comment by WenXin20** [comment]
I had the same problem. I'm using `Filters v1.1.0` and `Forge v28.1.40`
Although the end of the log says that the problem comes Doggy Talents, if you look at the time stamp `[23:01:55]`, you will find the `BUILDING_BLOCKS` error.
[latest.log](https://github.com/MrCrayfish/Filters/files/3700687/latest.log)

**Comment by MrCrayfish** [comment]
Fix coming in next version
